name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 18.x ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn run build:prod
      - name: linting typescript
        run: yarn run lint:ts
      - name: linting css
        run: yarn run lint:scss
      - name: unit testing
        run: yarn run test:unit







